version: '3.8'
services:
  db:
    image: registry.redhat.io/rhel8/postgresql-12
    volumes:
      - postgres_data:/var/lib/pgsql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - '.env'

  grafana:
    image: quay.io/digitronik/grafana-infinity:8.5.13
    expose:
      - 3000
      - 8000
    ports:
      - 3000:3000
    env_file:
      - '.env'
    environment:
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

  backend:
    image: sitreps/server-local:latest
    build:
      context: .
#      dockerfile: docker/Dockerfile.server
      dockerfile: docker/Dockerfile.server.local
    # wait for postgres
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 2; done; alembic upgrade head && uvicorn sitreps_server.main:app --host 0.0.0.0'
    ports:
      - 8000:8000
    volumes:
      - ./:/sitreps:z
    env_file:
      - '.env'
    environment:
      # Overwrite server coming from .env file so it will be network.
      - POSTGRESQL_SERVER=db
    depends_on:
      - db
      - grafana

volumes:
  postgres_data:
  grafana_data:
