version: '3.8'
services:
  db:
    image: registry.redhat.io/rhel8/postgresql-13
    volumes:
      - postgres_data:/var/lib/psql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - '.env'

  grafana:
    image: registry.redhat.io/rhel8/grafana:7-32
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana

  backend:
    build: .
    image: quay.io/digitronik/sitreps-backend:main
    ports:
      - 8000:8000
    env_file:
      - '.env'
    depends_on:
      - db
      - grafana

volumes:
  postgres_data:
  grafana_data:
