repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
    - id: reorder-python-imports
      language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3
      additional_dependencies: [flake8-comprehensions]
      args:
        - "--max-line-length=100"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    - id: mypy
      additional_dependencies: [types-all, types-attrs]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      args: [--safe, --quiet, --line-length, "100"]
      language_version: python3
      require_serial: true
