"""first commit

Revision ID: 4303eb5b92f2
Revises:
Create Date: 2023-05-22 16:32:03.420952

"""
# revision identifiers, used by Alembic.
revision = "4303eb5b92f2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
