"""First revision

Revision ID: 484dc575d02a
Revises:
Create Date: 2023-05-22 17:56:42.088733

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "484dc575d02a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
