"""rapidast_plugin

Revision ID: a3a53a80a82a
Revises: ab433409e1c2
Create Date: 2023-09-29 13:06:49.223708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a53a80a82a'
down_revision = 'ab433409e1c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapidast_report', sa.Column('plugin_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapidast_report', 'plugin_name')
    # ### end Alembic commands ###
