"""rapidast

Revision ID: ab433409e1c2
Revises: e8624bae336c
Create Date: 2023-08-09 16:05:58.957176

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "ab433409e1c2"
down_revision = "e8624bae336c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
