"""sonar_last_analysis

Revision ID: c0fd1ce16465
Revises: 484dc575d02a
Create Date: 2023-05-27 15:26:06.152247

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "c0fd1ce16465"
down_revision = "484dc575d02a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("sonar_last_analysis", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "sonar_last_analysis")
    # ### end Alembic commands ###
