"""req-portal

Revision ID: e8624bae336c
Revises: c0fd1ce16465
Create Date: 2023-05-31 21:32:10.535895

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e8624bae336c"
down_revision = "c0fd1ce16465"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
