{
 "title": "Interact code coverage",
 "tags": [ "23.06.07" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SelectedRepo",
    "label": "Selected Repository",
    "query": "insights-advisor-frontend, compliance-frontend, insights-dashboard, insights-inventory-frontend, malware-detection-frontend, ocp-advisor-frontend, patchman-ui, policies-ui-frontend, registration-assistant, insights-remediations-frontend, sed-frontend, tasks-frontend, vuln4shift-frontend, vulnerability-ui"
   }
  ]
 },
 "panels": [
  {
   "title": "Code Coverage (click to display historical data)",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    r.title AS repository_title, \n    cc.coverage, \n    cc.time\nFROM \n    repositories r\nJOIN \n    codecoverage cc ON r.id = cc.repository_id\nJOIN \n    projects p ON r.project_id = p.id\nWHERE \n    r.type = 'Development'\n    AND ((r.title='insights-advisor-frontend')\n    OR (r.title='compliance-frontend')\n    OR (r.title='drift-frontend')\n    OR (r.title='insights-dashboard')\n    OR (r.title='insights-inventory-frontend')\n    OR (r.title='kraken-ui')\n    OR (r.title='malware-detection-frontend')\n    OR (r.title='uhc-portal')\n    OR (r.title='ocp-advisor-frontend')\n    OR (r.title='console')\n    OR (r.title='patchman-ui')\n    OR (r.title='policies-ui-frontend')\n    OR (r.title='registration-assistant')\n    OR (r.title='insights-remediations-frontend')\n    OR (r.title='sed-frontend')\n    OR (r.title='tasks-frontend')\n    OR (r.title='vuln4shift-frontend')\n    OR (r.title='vulnerability-ui'))\n    AND cc.time = (\n        SELECT MAX(cc_inner.time)\n        FROM codecoverage cc_inner\n        WHERE cc_inner.repository_id = r.id\n    )\nORDER BY \n    cc.coverage DESC;"
    }
   ]
  },
  {
   "title": "Code Coverage & Unit Tests",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH LatestCodeCoverage AS (\n    SELECT \n        cc.repository_id, \n        cc.coverage, \n        cc.time,\n        ROW_NUMBER() OVER (PARTITION BY cc.repository_id ORDER BY cc.time DESC) AS rn\n    FROM \n        codecoverage cc\n),\nLatestUnitTests AS (\n    SELECT \n        ut.repository_id, \n        COALESCE(ut.jenkins, 0) + COALESCE(ut.travis, 0) + COALESCE(ut.other, 0) AS unittests_count,\n        ROW_NUMBER() OVER (PARTITION BY ut.repository_id ORDER BY ut.time DESC) AS rn\n    FROM \n        unittests ut\n)\nSELECT \n    r.title AS repository_title,\n    r.name AS repository_name, \n    lc.coverage, \n    lu.unittests_count\nFROM \n    repositories r\nJOIN \n    LatestCodeCoverage lc ON r.id = lc.repository_id AND lc.rn = 1\nLEFT JOIN \n    LatestUnitTests lu ON r.id = lu.repository_id AND lu.rn = 1\nJOIN \n    projects p ON r.project_id = p.id\nWHERE \n    r.type = 'Development'\n    AND ((r.title='insights-advisor-frontend')\n    OR (r.title='compliance-frontend')\n    OR (r.title='drift-frontend')\n    OR (r.title='insights-dashboard')\n    OR (r.title='insights-inventory-frontend')\n    OR (r.title='kraken-ui')\n    OR (r.title='malware-detection-frontend')\n    OR (r.title='uhc-portal')\n    OR (r.title='ocp-advisor-frontend')\n    OR (r.title='console')\n    OR (r.title='patchman-ui')\n    OR (r.title='policies-ui-frontend')\n    OR (r.title='registration-assistant')\n    OR (r.title='insights-remediations-frontend')\n    OR (r.title='sed-frontend')\n    OR (r.title='tasks-frontend')\n    OR (r.title='vuln4shift-frontend')\n    OR (r.title='vulnerability-ui'))\nORDER BY \n    r.title;"
    }
   ]
  },
  {
   "title": "Historical coverage data for $SelectedRepo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n    r.title AS repository_title, \n    cc.coverage, \n    ut.jenkins,\n    ut.travis,\n    ut.other,\n    cc.time\nFROM \n    repositories r\nJOIN \n    unittests ut ON r.id = ut.repository_id\nJOIN \n    codecoverage cc ON r.id = cc.repository_id\nJOIN \n    projects p ON r.project_id = p.id\nWHERE \n    r.type = 'Development'\n    AND (r.title='$SelectedRepo')\n    AND $__timeFilter(cc.time) \nORDER BY \n    cc.coverage DESC;"
    }
   ]
  }
 ]
}