{
 "title": "Sitreps",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Projects Group", "query": "select title from groups" },
   {
    "name": "group_id",
    "query": "select id from groups where title='$group'"
   },
   {
    "name": "project",
    "label": "Projects",
    "query": "select title from projects where group_id='$group_id'"
   },
   {
    "name": "project_id",
    "query": "select id from projects where title = '$project'"
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": "select name from repositories where project_id='$project_id'"
   },
   {
    "name": "test_repository",
    "label": "Test Repository",
    "query": "select name from repositories where project_id='$project_id' and type='test'"
   },
   {
    "name": "test_repository_id",
    "label": "Test Repository ID",
    "query": "select id from repositories where name='$test_repository'"
   }
  ]
 },
 "panels": [
  { "title": "Integration Test: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Automation Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Automation Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Test  Importance Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Test Importance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Interface Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Test Type Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Test Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Negative Tests",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", negative\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Missing Metadata",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", missing_assignee, missing_automation_status, missing_component, missing_importance, missing_interface_type, missing_requirements, missing_type\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Customer Scenario",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", customer_scenario\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Assignees",
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT assignees\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "project \"Tests\"=\"id\", \"Automation Status\"=\"automation_status\", \"Importance\"=\"importance\", \"Test Type\"=\"type\", \"Interface Type\"=\"interface_type\", \"Assignee\"=\"assignee\", \"is Negative\"=\"negative\", \"Time\"=\"create_at\"\n",
     "url": "http://sitreps-backend.insights-qe-sitreps.svc:8000/api/v1/metadata/$test_repository_id",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Code Coverage: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Coverage",
     "type": "gauge",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Code Coverage",
     "type": "timeseries",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  },
  {
   "title": "CLOC: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "CLOC Status",
     "type": "gauge",
     "description": "Current count of CLOC",
     "gridPos": { "h": 15, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "CLOC",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Jira: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jira: Total Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", resolved, unresolved, rejected\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: Total Metrics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", resolved, unresolved, rejected\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: Current Status",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, blocked, in_progress, code_review, on_qa, release_pending\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: Current",
     "type": "timeseries",
     "description": "Current status",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, blocked, in_progress, code_review, on_qa, release_pending\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: Created Status",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", created_last_15d, created_last_30d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: Created",
     "type": "timeseries",
     "description": "Created jira in last 15 and 30 days.",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", created_last_15d, created_last_30d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: ToDo Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, todo_older_than_30d, todo_older_than_60d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Jira: ToDo",
     "type": "timeseries",
     "description": "ToDo's\nCurrent, Last 30d and Last 60d",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, todo_older_than_30d, todo_older_than_60d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  },
  { "title": "SonarQube: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Unit Tests: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true
  }
 ]
}