{
 "title": "Sitreps",
 "description": "Situation Reports",
 "tags": [
  "23.05.12",
  "23.06.07"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Project Group",
    "query": "SELECT name AS __text, id AS __value\nFROM groups\nUNION ALL\nSELECT 'All' AS __text, 0 AS __value\nORDER BY __text;"
   },
   {
    "name": "manager",
    "label": "Managers",
    "query": "SELECT 'All' AS __text, 'All' AS __value\nUNION ALL\nSELECT DISTINCT \nCOALESCE(manager_name, 'Unknown') AS __text, \nCOALESCE(manager_name, 'Unknown') AS __value\nFROM projects\nWHERE \n  CASE\n    WHEN $group = 0 THEN true\n    ELSE group_id = $group\n  END\nORDER BY __text;"
   },
   {
    "name": "project",
    "label": "Projects",
    "query": "SELECT title AS __text, id AS __value\nFROM projects\nWHERE \n  ($group = 0 OR group_id = $group)\n  AND\n  ('$manager' = 'All' OR COALESCE(manager_name, 'Unknown') = '$manager')\nORDER BY __text;"
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": "SELECT title FROM repositories WHERE project_id = $project"
   },
   {
    "name": "test_repository",
    "label": "Test Repository",
    "query": "select name from repositories where project_id='$project' and type='Testing Plugin'"
   },
   {
    "name": "test_repository_id",
    "label": "Test Repository ID",
    "query": "SELECT id FROM repositories WHERE project_id = $project AND type = 'Test Plugin';"
   },
   {
    "name": "plugin_name",
    "query": "select name from projects where id = '$project'"
   },
   { "name": "env", "label": "Environment", "query": "stage,prod,fedramp" },
   {
    "name": "issue_type",
    "query": "SELECT\n    type AS __value,\n    CASE\n        WHEN type = 'qe' THEN 'QE Tasks'\n        WHEN type = 'dev' THEN 'Development Bugs'\n        ELSE type -- for other types, use the type as the text\n    END AS __text\nFROM jira\nWHERE project_id = $project\nGROUP BY type;"
   },
   {
    "name": "repositories",
    "query": "SELECT name AS __text, id AS __value\nFROM repositories\nWHERE project_id=$project\nORDER BY __text;"
   },
   {
    "name": "avg",
    "query": "Overall 24 Hr : overall-1,Core Functionality 24 Hr : core-1,Overall 7 Days  : overall-7,Core Functionality 7 Days : core-7,Overall 30 Days : overall-30,Core Functionality 30 Days : core-30"
   }
  ]
 },
 "panels": [
  {
   "title": "Requirements Summary: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$avg Avg [$env]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "repeat": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time, passed, xpass, skip, blocked, failed, xfailed, error, manual\nFROM req_portal\nWHERE env='$env' AND avg=$avg AND plugin='$plugin_name' ORDER BY 1"
      }
     ]
    },
    {
     "title": "$avg Avg Historical Data [$env]",
     "type": "timeseries",
     "description": "It's a historical representation of the 7-day overall avg. Data points represent the 7-day average at that respective time. ",
     "gridPos": { "h": 8, "w": 18, "x": 5, "y": 1 },
     "repeat": "avg",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT time, passed, xpass, skip, blocked, failed, xfailed, error, manual\nFROM req_portal\nWHERE\n  $__timeFilter(\"time\") AND env='$env' AND avg=$avg AND plugin='$plugin_name' ORDER BY 1",
       "source": "url",
       "type": "json",
       "url": "https://jsonplaceholder.typicode.com/users",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Integration Test: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last 7 Days",
     "type": "stat",
     "description": "Make sure 7 days of data available",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT l.total_tests - f.total_tests AS \"New Tests\", l.automated - f.automated AS \"Automated\", l.not_automated - f.not_automated AS \"Non-Automated\", l.manual_only - f.manual_only AS \"Manual-Only\" FROM \n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '7 days' ORDER BY time ASC LIMIT 1) f,\n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '7 days' ORDER BY time DESC LIMIT 1) l"
      }
     ]
    },
    {
     "title": "Last 15 Days",
     "type": "stat",
     "description": "Make sure 15 days of data available",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT l.total_tests - f.total_tests AS \"New Tests\", l.automated - f.automated AS \"Automated\", l.not_automated - f.not_automated AS \"Non-Automated\", l.manual_only - f.manual_only AS \"Manual-Only\" FROM \n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '15 days' ORDER BY time ASC LIMIT 1) f,\n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '15 days' ORDER BY time DESC LIMIT 1) l"
      }
     ]
    },
    {
     "title": "Automation Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Automation Trends",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Test  Importance Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Test Importance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Interface Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Interface Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Test Type Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Test Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Assignees",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
     "targets": [
      {
       "rawSql": "WITH json_data AS (\n    SELECT\n        assignees::jsonb AS assignee_count\n    FROM tests\n    WHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n    LIMIT 1\n)\nSELECT\n    jsonb_object_keys(assignee_count) AS \"Assignee\",\n    (assignee_count ->> jsonb_object_keys(assignee_count))::integer AS \"Tests Count\"\nFROM json_data;"
      }
     ]
    },
    {
     "title": "Negative Tests",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 8, "x": 6, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", negative\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
      }
     ]
    },
    {
     "title": "Customer Scenario",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", customer_scenario\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
      }
     ]
    },
    {
     "title": "Missing Metadata",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 18, "x": 6, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", missing_assignee, missing_automation_status, missing_component, missing_importance, missing_interface_type, missing_requirements, missing_type\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Metadata",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "columns": [
        { "selector": "id", "text": "Tests", "type": "string" },
        { "selector": "automation_status", "text": "Automation Status", "type": "string" },
        { "selector": "importance", "text": "Importance", "type": "string" },
        { "selector": "type", "text": "Type", "type": "string" },
        { "selector": "interface_type", "text": "Interface Type", "type": "string" },
        { "selector": "assignee", "text": "Assignee", "type": "string" },
        { "selector": "negative", "text": "Negative", "type": "string" },
        { "selector": "component", "text": "Component", "type": "string" }
       ],
       "source": "url",
       "type": "json",
       "uql": "project \"Tests\"=\"id\", \"Automation Status\"=\"automation_status\", \"Importance\"=\"importance\", \"Test Type\"=\"type\", \"Interface Type\"=\"interface_type\", \"Assignee\"=\"assignee\", \"is Negative\"=\"negative\", \"Component\"=\"component\", \"Time\"=\"create_at\"\n",
       "url": "${SITREPS_HOSTNAME}/api/v1/metadata/$test_repository_id",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "CLOC Status",
     "type": "gauge",
     "description": "Current count of CLOC",
     "gridPos": { "h": 15, "w": 5, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CLOC",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 59 },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "CLOC: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CLOC Status",
     "type": "gauge",
     "description": "Current count of CLOC",
     "gridPos": { "h": 15, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CLOC-$repositories",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 5, "y": 3 },
     "repeat": "repositories",
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", cloc FROM cloc WHERE repository_id=$repositories AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Code Coverage: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Coverage",
     "type": "gauge",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Code Coverage",
     "type": "timeseries",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id = repositories.id \nWHERE repositories.project_id = $project AND $__timeFilter(\"time\")\nORDER BY 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Unit Tests: $project ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unit Tests Count",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT unittests.time AS \"time\",\n(COALESCE(unittests.gh_action, 0) + COALESCE(unittests.jenkins, 0) + COALESCE(unittests.travis, 0) + COALESCE(unittests.other, 0)) AS \"unit-tests\",\nrepositories.name\nFROM unittests INNER JOIN repositories ON unittests.repository_id = repositories.id\nWHERE repositories.project_id = $project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Unit Tests ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 5, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT unittests.time AS \"time\",\n(COALESCE(unittests.gh_action, 0) + COALESCE(unittests.jenkins, 0) + COALESCE(unittests.travis, 0) + COALESCE(unittests.other, 0)) AS \"unit-tests\",\nrepositories.name\nFROM unittests INNER JOIN repositories ON unittests.repository_id = repositories.id\nWHERE repositories.project_id = $project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Jira: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jira  [$issue_type]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 22 },
     "repeat": "issue_type",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  time AS \"time\",\n  resolved AS \"Resolved\",\n  unresolved AS \"Unresolved\",\n  rejected AS \"Rejected\", \n  todo AS \"ToDo\", \n  blocked AS \"Blocked\", \n  in_progress AS \"In Progress\",\n  code_review AS \"Code Review\",\n  on_qa AS \"On QA\",\n  release_pending AS \"Release Pending\",\n  created_last_15d AS \"Created in last 15 days\", \n  created_last_30d AS \"Created in last 30 days\",\n  todo_older_than_30d AS \"ToDo from last 30 days\", \n  todo_older_than_60d AS \"ToDo from last 60 days\"\nFROM jira \nWHERE project_id=$project AND type=$issue_type AND $__timeFilter(\"time\")\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Jira Trends [$issue_type]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 18, "x": 6, "y": 22 },
     "repeat": "issue_type",
     "targets": [
      {
       "rawSql": "SELECT \n  time AS \"time\",\n  resolved AS \"Resolved\",\n  unresolved AS \"Unresolved\",\n  rejected AS \"Rejected\", \n  todo AS \"ToDo\", \n  blocked AS \"Blocked\", \n  in_progress AS \"In Progress\",\n  code_review AS \"Code Review\",\n  on_qa AS \"On QA\",\n  release_pending AS \"Release Pending\",\n  created_last_15d AS \"Created in last 15 days\", \n  created_last_30d AS \"Created in last 30 days\",\n  todo_older_than_30d AS \"ToDo from last 30 days\", \n  todo_older_than_60d AS \"ToDo from last 60 days\"\nFROM jira \nWHERE project_id=$project AND type=$issue_type AND $__timeFilter(\"time\")\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "SonarQube: $project  ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT r.title as \"Repository Name\", sq.sonar_last_analysis as \"Last Sonar Analysis\"        \nFROM (\n    SELECT repository_id, MAX(time) AS latest_time\n    FROM sonarqube\n    GROUP BY repository_id\n) AS latest\nINNER JOIN sonarqube sq ON latest.repository_id = sq.repository_id AND latest.latest_time = sq.time\nINNER JOIN repositories r ON sq.repository_id = r.id\nWHERE r.project_id = $project "
      }
     ]
    },
    {
     "title": "SonarQube: Security Hotspots",
     "type": "bargauge",
     "description": "0 - 1 : Green \n2 - 5: Yello\n5 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.security_hotspots, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Security Hotspots",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.security_hotspots, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Vulnerabilities",
     "type": "bargauge",
     "description": "0 - 1 : Green \n2 - 5: Yello\n5 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.vulnerabilities, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.vulnerabilities, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Bugs",
     "type": "bargauge",
     "description": "0 - 5 : Green \n6 - 15: Yello\n15 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.bugs, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Bugs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.bugs, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Code Smells",
     "type": "bargauge",
     "description": "0 - 50 : Green \n51 - 100: Yello\n100 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.code_smells, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Code Smells",
     "type": "timeseries",
     "description": "0 - 50 : Green \n51 - 100: Yello\n100 > :  Red",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 64 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.code_smells, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}