{
 "title": "Sitreps",
 "description": "Situation Reports",
 "tags": [ "23.05.12" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Projects Group", "query": "select title from groups" },
   {
    "name": "group_id",
    "query": "select id from groups where title='$group'"
   },
   {
    "name": "project",
    "label": "Projects",
    "query": "select title from projects where group_id='$group_id'"
   },
   {
    "name": "project_id",
    "query": "select id from projects where title = '$project'"
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": "select name from repositories where project_id='$project_id'"
   },
   {
    "name": "test_repository",
    "label": "Test Repository",
    "query": "select name from repositories where project_id='$project_id' and type='test'"
   },
   {
    "name": "test_repository_id",
    "label": "Test Repository ID",
    "query": "select id from repositories where name='$test_repository'"
   }
  ]
 },
 "panels": [
  { "title": "Integration Test: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last 7 Days",
   "type": "bargauge",
   "description": "Make sure 7 days of data available",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT l.total_tests - f.total_tests AS \"New Tests\", l.automated - f.automated AS \"Automated\", l.not_automated - f.not_automated AS \"Non-Automated\", l.manual_only - f.manual_only AS \"Manual-Only\" FROM \n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '7 days' ORDER BY time ASC LIMIT 1) f,\n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '7 days' ORDER BY time DESC LIMIT 1) l"
    }
   ]
  },
  {
   "title": "Last 15 Days",
   "type": "bargauge",
   "description": "Make sure 15 days of data available",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT l.total_tests - f.total_tests AS \"New Tests\", l.automated - f.automated AS \"Automated\", l.not_automated - f.not_automated AS \"Non-Automated\", l.manual_only - f.manual_only AS \"Manual-Only\" FROM \n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '15 days' ORDER BY time ASC LIMIT 1) f,\n(SELECT total_tests, automated, not_automated, manual_only FROM tests WHERE repository_id=$test_repository_id AND time > current_date - interval '15 days' ORDER BY time DESC LIMIT 1) l"
    }
   ]
  },
  {
   "title": "Automation Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Automation Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", automated, not_automated, manual_only\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Test  Importance Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Test Importance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", critical, high, medium, low\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Interface Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", ui, non_ui\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Test Type Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Test Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", functional, non_functional\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Negative Tests",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", negative\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Missing Metadata",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", missing_assignee, missing_automation_status, missing_component, missing_importance, missing_interface_type, missing_requirements, missing_type\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Customer Scenario",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", customer_scenario\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Assignees",
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT assignees\nFROM tests\nWHERE repository_id=$test_repository_id AND $__timeFilter(\"time\")\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "project \"Tests\"=\"id\", \"Automation Status\"=\"automation_status\", \"Importance\"=\"importance\", \"Test Type\"=\"type\", \"Interface Type\"=\"interface_type\", \"Assignee\"=\"assignee\", \"is Negative\"=\"negative\", \"Component\"=\"component\", \"Time\"=\"create_at\"\n",
     "url": "http://sitreps-backend.insights-qe-sitreps.svc:8000/api/v1/metadata/$test_repository_id",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "CLOC: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "CLOC Status",
     "type": "gauge",
     "description": "Current count of CLOC",
     "gridPos": { "h": 15, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CLOC",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT cloc.time AS \"time\", cloc.cloc, repositories.name FROM cloc INNER JOIN repositories ON cloc.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Code Coverage: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Coverage",
     "type": "gauge",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Code Coverage",
     "type": "timeseries",
     "description": "Code Coverage Trends",
     "gridPos": { "h": 14, "w": 18, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT codecoverage.time AS \"time\", codecoverage.coverage, repositories.name\nFROM codecoverage INNER JOIN repositories ON codecoverage.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Unit Tests: $project ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unit Tests Count",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT unittests.time AS \"time\",\nunittests.other AS \"unit-tests\",\nrepositories.name\nFROM unittests INNER JOIN repositories ON unittests.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Unit Tests ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 5, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT unittests.time AS \"time\",\nunittests.other AS \"unit-tests\",\nrepositories.name\nFROM unittests INNER JOIN repositories ON unittests.repository_id=repositories.id\nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Jira: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jira: Total Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", resolved, unresolved, rejected\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: Total Metrics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", resolved, unresolved, rejected\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: Current Status",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, blocked, in_progress, code_review, on_qa, release_pending\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: Current",
     "type": "timeseries",
     "description": "Current status",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, blocked, in_progress, code_review, on_qa, release_pending\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: Created Status",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", created_last_15d, created_last_30d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: Created",
     "type": "timeseries",
     "description": "Created jira in last 15 and 30 days.",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", created_last_15d, created_last_30d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: ToDo Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, todo_older_than_30d, todo_older_than_60d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Jira: ToDo",
     "type": "timeseries",
     "description": "ToDo's\nCurrent, Last 30d and Last 60d",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT time AS \"time\", todo, todo_older_than_30d, todo_older_than_60d\nFROM jira \nWHERE project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "SonarQube: $project  ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "SonarQube: Security Hotspots",
     "type": "bargauge",
     "description": "0 - 1 : Green \n2 - 5: Yello\n5 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.security_hotspots, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Security Hotspots",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.security_hotspots, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Vulnerabilities",
     "type": "bargauge",
     "description": "0 - 1 : Green \n2 - 5: Yello\n5 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.vulnerabilities, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.vulnerabilities, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Bugs",
     "type": "bargauge",
     "description": "0 - 5 : Green \n6 - 15: Yello\n15 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.bugs, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Bugs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.bugs, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube: Code Smells",
     "type": "bargauge",
     "description": "0 - 50 : Green \n51 - 100: Yello\n100 > :  Red",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.code_smells, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    },
    {
     "title": "SonarQube Trends: Code Smells",
     "type": "timeseries",
     "description": "0 - 50 : Green \n51 - 100: Yello\n100 > :  Red",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT sonarqube.time AS \"time\", sonarqube.code_smells, repositories.name\nFROM sonarqube INNER JOIN repositories ON sonarqube.repository_id=repositories.id \nWHERE repositories.project_id=$project_id AND $__timeFilter(\"time\")\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}