FROM registry.access.redhat.com/ubi8/python-39

USER 0
WORKDIR /sitreps/

COPY sitreps_server sitreps_server
COPY requirements.txt requirements.txt
COPY alembic.ini alembic.ini
COPY alembic alembic

RUN pip install -r requirements.txt

EXPOSE 8000
EXPOSE 5432

USER 1001

CMD ["uvicorn", "sitreps_server.main:app", "--host","0.0.0.0", "--port","8000"]
