ARG GRAFANA_VERSION="10.3.6"

FROM grafana/grafana-enterprise:${GRAFANA_VERSION}

USER grafana

ARG GF_INSTALL_PLUGINS="yesoreyeram-infinity-datasource"

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi
