{
 "title": "Sitreps",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Projects Group", "query": "select title from groups" },
   {
    "name": "group_id",
    "query": "select id from groups where title='$group'"
   },
   {
    "name": "project",
    "label": "Projects",
    "query": "select title from projects where group_id='$group_id'"
   },
   {
    "name": "project_id",
    "query": "select id from projects where title = '$project'"
   },
   {
    "name": "sonarqube_repos",
    "query": "select distinct repo_name from sonarqube where project_id='$project_id'"
   },
   {
    "name": "unittest_repos",
    "query": "select distinct repo_name from unittests where project_id='$project_id'"
   },
   { "name": "unique", "query": "True,False" }
  ]
 },
 "panels": [
  {
   "title": "Total Tests",
   "type": "stat",
   "description": "All test cases including parallelization. ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"all\",\n  automated,\n  manual\nFROM tests\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  \"unique\" = False\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Unique Tests",
   "type": "stat",
   "description": "All test cases without parallelization. ",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"all\",\n  automated,\n  manual\nFROM tests\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  \"unique\" = True\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Missing Metadata Test Count",
   "type": "bargauge",
   "description": "All test cases without parallelization. ",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  missing_assignee,\n  missing_casecomponent,\n  missing_caseimportance,\n  missing_interfacetype,\n  missing_requirements\nFROM tests\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  \"unique\" = False\nORDER BY 1"
    }
   ]
  },
  { "title": "CLOC: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Count Line of Code",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  repo_name,\n  cloc\nFROM cloc\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Count Line of Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  repo_name,\n  cloc\nFROM cloc\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id'\nORDER BY 1"
    }
   ]
  },
  { "title": "Jira: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Jira Status: $project",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  todo,\n  in_progress,\n  code_review,\n  on_qa,\n  blocked,\n  unresolved\nFROM jira\nWHERE\n  project_id = '$project_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Jira Metrics: $project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  todo,\n  in_progress,\n  code_review,\n  on_qa,\n  blocked,\n  unresolved,\n  resolved,\n  todo_older_than_60d,\n  resolved_last_month,\n  created_last_month\nFROM jira\nWHERE\n  project_id = '$project_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SonarQube: $project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$project : $sonarqube_repos",
     "type": "gauge",
     "description": "patchman-ui repository sonarqube status",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "repeat": "sonarqube_repos",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  security_hotspots,\n  vulnerabilities,\n  bugs,\n  code_smells\nFROM sonarqube\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  repo_name = '${sonarqube_repos:raw}'\nORDER BY 1"
      }
     ]
    },
    {
     "title": "sonarqube: $sonarqube_repos",
     "type": "timeseries",
     "description": "patchman-ui repository sonarqube status",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
     "repeat": "sonarqube_repos",
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"time\",\n  security_hotspots,\n  vulnerabilities,\n  bugs,\n  code_smells\nFROM sonarqube\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  repo_name = '${sonarqube_repos:raw}'\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Unit Tests: $project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Unit Test Count: $project - $unittest_repos",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "repeat": "unittest_repos",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  gh_action + jenkins + travis as \"total\"\nFROM unittests\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  repo_name = '${unittest_repos:raw}'\n  ORDER BY 1"
    }
   ]
  },
  {
   "title": "Unit Test Count: $project - $unittest_repos",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 21 },
   "repeat": "unittest_repos",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  gh_action, jenkins, travis\nFROM unittests\nWHERE\n  $__timeFilter(\"time\") AND\n  project_id = '$project_id' AND\n  repo_name = '${unittest_repos:raw}'\n  ORDER BY 1"
    }
   ]
  }
 ]
}