# Template for grafana sitreps
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sitreps-grafana-template
# ===============================================
# Grafana
# ===============================================
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: grafana
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentConfig: grafana
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentConfig: grafana
      spec:
        containers:
        - env:
          image: registry.redhat.io/rhel8/grafana:7-32
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
          - containerPort: 3000
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - grafana
        from:
          kind: ImageStreamTag
          name: grafana:7-32
      type: ImageChange

# -----------------------------------------------
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: grafana
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentConfig: grafana
# -----------------------------------------------
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: grafana
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${GRAFANA_STORAGE}

# -----------------------------------------------
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: grafana
    namespace: ${NAMESPACE}
    annotations:
      description: "A route to the grafana"
  spec:
    to:
      kind: Service
      name: grafana
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge

# ===============================================
# Parameters
# ===============================================
parameters:
- name: GRAFANA_STORAGE
  displayName: Grafana Storage
  description: The amount of storage space for the database to use
  value: 1Gi
- name: APP_NAME
  displayName: App Name
  description: The name of the application
  value: grafana
- name: NAMESPACE
  displayName: Namespace
  description: The namespace for all of the images, applications, etc.
  value: vmugicag
