name: Build and Push Image
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: sitreps-server
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./docker/Dockerfile.server

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/digitronik
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
