name: sitreps-server

on:
  push:
    branches:
      - main
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Pre-Commit Checks
        run: |
          python -m pip install pip --upgrade
          python -m pip install pre-commit
          pre-commit run -a

      - name: Analysis (git diff)
        if: failure()
        run: git diff
